#!/bin/bash

. activate tensorflow
python nn_const_data_fire_v4.py
. deactivate
sed -i -e "s/\\[/ /g" ~/codes/FIRE_CODES/fire_aggregateData/output_ssaplus/weights_ba.txt
sed -i -e "s/\\]/ /g" ~/codes/FIRE_CODES/fire_aggregateData/output_ssaplus/weights_ba.txt
sed -i -e "s/\\,/ /g" ~/codes/FIRE_CODES/fire_aggregateData/output_ssaplus/weights_ba.txt

