# makefile for fire model

TARGET = fire
LIBPATH = -L/usr/local/netcdf-cxx-legacy/lib -L/home/jaideep/codes/libgsm_v2/lib
INCPATH = -I/usr/local/netcdf-c-4.3.2/include -I/usr/local/netcdf-cxx-legacy/include
INCPATH += -I/home/jaideep/codes/libgsm_v2/include
LDFLAGS =  
CPPFLAGS = -g

CPPFILES = $(wildcard *.cpp) 
OBJFILES = $(CPPFILES:.cpp=.o)

LIBS = -l:libgsm.so.2 -lnetcdf_c++


all: $(TARGET)

$(TARGET): $(OBJFILES)
	g++ -o $(LDFLAGS) $(TARGET) $(OBJFILES) $(LIBPATH) $(LIBS)

.cpp.o:
	g++ -c $(CPPFLAGS) $(INCPATH) $< -o $@ 

clean:
	rm -f *.o $(TARGET)

re: clean all


